from report.metrics import period_metrics as pm
from report.metrics import profit_metrics as pfm
from report.metrics import risk_metrics as rm
from report.metrics import formatting as fm
from report.metrics import time_metrics as tm
import pandas as pd
df_trades = pd.read_parquet('../outputs/trades.parquet(1)')

print('='* 40)
print(f'Win rate: {(pfm.win_rate(df_trades)):.2f}%')
print(f'Profit: {(pfm.final_profit(df_trades)):.2f} pts')
print(f'Number of trades: {pfm.trades_number(df_trades)}')
print(f'Profit per Trade: {fm.format_points(pfm.profit_per_operations(df_trades))} ')
print(f'Win Trades: {pfm.win_trades_number(df_trades)} ')
print(f'Loss Trades: {pfm.loss_trades_number(df_trades)} ')
print(f'Breakeven Trades: {pfm.breakeven(df_trades)} ')
summary = pm.profit_by_time(df_trades)
summary['win_rate'] = summary['win_rate'].apply(fm.format_pct)
summary['profit'] = summary['profit'].apply(fm.format_points)
summary['average_profit'] = summary['average_profit'].apply(fm.format_points)
print(f'Profit per time (30min):\n{summary}')
print(f'Accumulated Profit: {rm.accumulated_profit(df_trades)} pts')
print(f'Highest Profit: {rm.highest_profit(df_trades)} pts')
print(f'Max Drawdown: {rm.drawdown(df_trades)} pts')
print(f'Average time per trade: {fm.format_min(tm.average_time(df_trades))}')
print(f'Max time per trade: {fm.format_min(tm.maximum_time(df_trades))} ')
print(f'Minimum time per trade: {fm.format_min(tm.minimum_time(df_trades))} ')
print(f'Profit per day: \n{pm.daily_profit(df_trades)}')
print(f'Profit per week: \n{pm.weekly_profit(df_trades)}')
print(f'Profit per month: \n{pm.monthly_profit(df_trades)}')
print(f'Number of trades per day:\n {pm.average_number_daily_trades(df_trades)}')
print(f'Number of trades per week:\n {pm.average_number_week_trades(df_trades)}')
print(f'Number of trades per month:\n {pm.average_number_month_trades(df_trades)}')
print(f'Average daily profit: {fm.format_points(pm.average_daily_profit(df_trades))} ')
print(f'Average weekly profit: {fm.format_points(pm.average_weekly_profit(df_trades))}')
print(f'Average monthly profit {pm.average_monthly_profit(df_trades)}')
print(f'Profit of my win trades: {fm.format_points(pfm.sum_win_trades(df_trades))} pts')
print(f'Profit of my loss: {pfm.sum_loss_trades(df_trades)} pts')
print(f'Profit Factor: {pfm.profit_factor(df_trades)} pts')
print(f'Expectancy: {pfm.expectancy_factor(df_trades)} pts')
print(f'Sharpe Ratio: {rm.sharpe_ratio(df_trades)} pts')
print(f'Sortino Ratio: {rm.sortino_ratio(df_trades)} pts')
print(f'Streak Losses: {rm.streak_losses(df_trades)} trades')
print(df_trades.tail())
print('='* 40)
